version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: news-portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1997
    ports:
      - "5432:5432"
